sudo: false
language: node_js
node_js:
- 6
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm i -g npm@latest
- npm i
script:
- npm start
cache:
  directories:
  - node_modules
