sudo: false
language: node_js
node_js:
- 6
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm i -g npm@latest
- npm i

before_script:
- export LERNA_VERSION==$(./version.sh)
script:
- npm run lerna:bootstrap
- if [[ $TRAVIS_BRANCH == "master" ]]; then npm run release; else npm start && npm test; fi
after_script:
cache:
  directories:
  - node_modules
